# Form implementation generated from reading ui file '.\uis\AdminsCRUD.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from db_operations import DatabaseManager

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 320)
        MainWindow.setMinimumSize(QtCore.QSize(420, 320))
        MainWindow.setMaximumSize(QtCore.QSize(420, 320))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(110, 90, 179, 22))
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(parent=self.splitter_2)
        self.label_2.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.txtemail = QtWidgets.QLineEdit(parent=self.splitter_2)
        self.txtemail.setObjectName("txtemail")
        self.splitter_4 = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter_4.setGeometry(QtCore.QRect(110, 190, 179, 22))
        self.splitter_4.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.btnConfAdmin = QtWidgets.QPushButton(parent=self.splitter_4)
        self.btnConfAdmin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.btnConfAdmin.setObjectName("btnConfAdmin")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(110, 50, 179, 22))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_3 = QtWidgets.QSplitter(parent=self.splitter)
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(parent=self.splitter_3)
        self.label_3.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.cmbUsers = QtWidgets.QComboBox(parent=self.splitter_3)
        self.cmbUsers.setObjectName("cmbUsers")
        self.splitter_5 = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter_5.setGeometry(QtCore.QRect(110, 130, 179, 22))
        self.splitter_5.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_4 = QtWidgets.QLabel(parent=self.splitter_5)
        self.label_4.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.splitter_5)
        self.txtPassword.setObjectName("txtPassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Email :"))
        self.btnConfAdmin.setText(_translate("MainWindow", "Confirmer"))
        self.label_3.setText(_translate("MainWindow", "User :"))
        self.label_4.setText(_translate("MainWindow", "Password :"))


from PyQt6.QtWidgets import QMainWindow, QMessageBox

class AdminCRUDWindow(QMainWindow):
    def __init__(self, parent=None):
        super(AdminCRUDWindow, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Initialize database manager
        self.db_manager = DatabaseManager()

        # Connect the "Confirmer" button to a method
        self.ui.btnConfAdmin.clicked.connect(self.confirm_admin)
        
        self.stat = ""
        self.idAdmin = 0

        self.load_Users()

    def confirm_admin(self):

        user_name, id_user = self.get_selected_user()
        email = self.ui.txtemail.text().strip()
        password = self.ui.txtPassword.text().strip()

        if not user_name or not email or not password :
                QMessageBox.warning(self, "Input Error", "All fields are required!")
                return
        if self.stat == "add":
            self.db_manager.add_admin(id_user,email,password)
            QMessageBox.information(self, "Success", f"Admin '{user_name}' has been Added successfully!")
        elif self.stat == "edit":
            self.db_manager.update_admin(self.idAdmin,id_user,email,password)
            QMessageBox.information(self, "Success", f"Admin '{user_name}' has been Updated successfully!")
        
        self.close()

    def populate_form(self, admin_data):

        self.idAdmin = int(admin_data["admin_id"])
        self.ui.cmbUsers.setCurrentText(admin_data.get("user", ""))
        self.ui.txtemail.setText(admin_data.get("email", ""))
        self.ui.txtPassword.setText(admin_data.get("password", ""))

    def load_Users(self):
        Users = self.db_manager.get_users_from_db()
        self.ui.cmbUsers.clear()

        for user_id, user_name in Users:
            self.ui.cmbUsers.addItem(user_name, user_id)  # Add the name as visible text and ID as associated data

    def get_selected_user(self):
        # Get the index of the currently selected item
        index = self.ui.cmbUsers.currentIndex()
        if index == -1:  # No selection
            return None, None

        user_name = self.ui.cmbUsers.currentText()

        user_id = self.ui.cmbUsers.itemData(index)

        return user_name, user_id




