# Form implementation generated from reading ui file '.\uis\DepartementCUD.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt6 import QtCore, QtGui, QtWidgets
from db_operations import DatabaseManager


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 320)
        MainWindow.setMinimumSize(QtCore.QSize(420, 320))
        MainWindow.setMaximumSize(QtCore.QSize(420, 320))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(110, 120, 179, 22))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(parent=self.splitter)
        self.label.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.txtdep = QtWidgets.QLineEdit(parent=self.splitter)
        self.txtdep.setObjectName("txtdep")
        self.btnConfDep = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConfDep.setGeometry(QtCore.QRect(150, 230, 93, 28))
        self.btnConfDep.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.btnConfDep.setObjectName("btnConfDep")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Departement :"))
        self.btnConfDep.setText(_translate("MainWindow", "Confirmer"))


from PyQt6.QtWidgets import QMainWindow, QMessageBox

class DepartementCRUDWindow(QMainWindow):
    def __init__(self, parent=None):
        super(DepartementCRUDWindow, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Initialize database manager
        self.db_manager = DatabaseManager()

        # Connect the "Confirmer" button to a method
        self.ui.btnConfDep.clicked.connect(self.confirm_user)
        
        self.stat = ""
        self.idDep = 0


    def confirm_user(self):

        id_dep = self.idDep
        name = self.ui.txtdep.text().strip()
        if not name:
                QMessageBox.warning(self, "Input Error", "The name are required!")
                return
        if self.stat == "add":
            self.db_manager.add_department(name)
            QMessageBox.information(self, "Success", f"Departement '{name}' has been Added successfully!")
        elif self.stat == "edit":
            self.db_manager.update_department(id_dep,name)
            QMessageBox.information(self, "Success", f"Departement '{name}' has been Updated successfully!")
        
        self.close()

    def populate_form(self, user_data):
        self.idDep = int(user_data["id_dep"])
        self.ui.txtdep.setText(user_data.get("name", ""))




